language: java
jdk:
  - openjdk8


before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust


before_deploy:
  - printf 'VER\t${project.version}' | mvn help:evaluate | grep '^VER' | cut -f2
  - export project_version=$(printf 'VER\t${project.version}' | mvn help:evaluate | grep '^VER' | cut -f2)

deploy:
  - provider: script
    script: bash .travis/deploy.sh
    on:
      repo: smartshark/jSHARK
      tags: true

  - provider: releases
    api_key:
      secure: m+c8As626rl+Dm6jymiouCb/PkBF2EwwS/W3IHqCcEIsqo56W2ltp9sJ37gvqNeigi2GGZ20DOQsE3eQZA4tCnrtv03swtccJyAwJqG5ShnJJJ4p1iKdp5UOJqlmbe6NgQd5YZv58mWRyEUqqYwN3AL0CfojJDHQSSklrLKavqyqoMISm+cW3q0/ufBvDCXfQ9b68r6XleFXTyFnzSVlKPflOW18e/fnRH6e2R1GNsk4O1AwBCQOGBUJ6nHWIeD9OHtnYELhUlrKIL3Fnhe7wCC1a6Z/rYlhmjuIZywzEeXsWIxTTUXZU8wgv+XkJ+IlqNWjVZcu3lPlUCFSin1KtggE5HaIyI4cScxrCDaSkTHwKvYSmkbqQvJQo/ky2t34cQ3RKqoKgikptmXQpP8lQ4u589T8Xzw3gkXEKD8U7Gf2bsQ0WF0clabr6uXYcXGjxvP8p5Ec3p7qDiqFzbsa21xraMlan2FXhKgrQU8M/UjzGa+FWA5quXuPnVFES3uh46HWTMbDZB/rbFNNhIO9wBLx8eWrIgo2LU7VsHyf7Bb/KEzrxdhkJit8KL7BMzquyGfKthYbw6diP3BBbb0D0BiAqD6MltANFvQumnAYRjPdGNsRzVT0GRlLtIw0qINZfua7BdbUOH7wqzck7xVgNYg6kq48bNj2OlZVVlCQdYs=
    file: target/jSHARK-$project_version.jar
    skip_cleanup: true
    on:
      repo: smartshark/jSHARK
      tags: true